import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/food_item.dart';

/// Food Data Seeder
/// Helper class to populate Firestore with initial food items
class FoodDataSeeder {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  /// Seed all food items to Firestore
  Future<void> seedFoodItems() async {
    final foodItems = _getAllFoodItems();
    
    final batch = _db.batch();
    
    for (final item in foodItems) {
      final docRef = _db.collection('foodItems').doc(item.id);
      batch.set(docRef, item.toMap());
    }
    
    await batch.commit();
    print('✅ Seeded ${foodItems.length} food items to Firestore');
  }

  List<FoodItem> _getAllFoodItems() {
    return [
      // ========== DESI FOOD ==========
      FoodItem(
        id: 'desi_001',
        name: 'Chicken Biryani',
        category: 'Desi Food',
        subCategory: 'Most Liked',
        price: 250,
        imageUrl: '🍛',
        description: 'Aromatic basmati rice with tender chicken pieces',
        rating: 4.8,
        reviews: 245,
        tags: ['spicy', 'rice', 'popular'],
        isPromotional: true,
        discountPrice: 220,
      ),
      FoodItem(
        id: 'desi_002',
        name: 'Mutton Karahi',
        category: 'Desi Food',
        price: 350,
        imageUrl: '🍲',
        description: 'Spicy mutton cooked in traditional karahi style',
        rating: 4.7,
        reviews: 189,
        tags: ['spicy', 'meat', 'traditional'],
      ),
      FoodItem(
        id: 'desi_003',
        name: 'Nihari',
        category: 'Desi Food',
        subCategory: 'Seasonal',
        price: 300,
        imageUrl: '🥘',
        description: 'Slow-cooked beef stew with aromatic spices',
        rating: 4.9,
        reviews: 312,
        tags: ['spicy', 'beef', 'traditional'],
        isSeasonal: true,
      ),
      FoodItem(
        id: 'desi_004',
        name: 'Haleem',
        category: 'Desi Food',
        price: 200,
        imageUrl: '🍜',
        description: 'Thick lentil and meat stew',
        rating: 4.6,
        reviews: 156,
        tags: ['healthy', 'traditional'],
      ),
      FoodItem(
        id: 'desi_005',
        name: 'Chicken Tikka',
        category: 'Desi Food',
        subCategory: 'Most Liked',
        price: 280,
        imageUrl: '🍗',
        description: 'Grilled marinated chicken pieces',
        rating: 4.8,
        reviews: 298,
        tags: ['grilled', 'spicy', 'popular'],
      ),
      FoodItem(
        id: 'desi_006',
        name: 'Seekh Kebab',
        category: 'Desi Food',
        price: 180,
        imageUrl: '🥙',
        description: 'Minced meat kebabs with spices',
        rating: 4.5,
        reviews: 134,
        tags: ['grilled', 'meat'],
      ),
      FoodItem(
        id: 'desi_007',
        name: 'Palak Paneer',
        category: 'Desi Food',
        price: 220,
        imageUrl: '🥬',
        description: 'Spinach curry with cottage cheese',
        rating: 4.4,
        reviews: 98,
        tags: ['vegetarian', 'healthy'],
      ),
      FoodItem(
        id: 'desi_008',
        name: 'Dal Makhani',
        category: 'Desi Food',
        price: 150,
        imageUrl: '🫘',
        description: 'Creamy black lentils',
        rating: 4.6,
        reviews: 167,
        tags: ['vegetarian', 'healthy'],
      ),

      // ========== FAST FOOD ==========
      FoodItem(
        id: 'fast_001',
        name: 'Zinger Burger',
        category: 'Fast Food',
        subCategory: 'Most Liked',
        price: 280,
        imageUrl: '🍔',
        description: 'Crispy fried chicken burger with special sauce',
        rating: 4.7,
        reviews: 421,
        tags: ['chicken', 'popular', 'crispy'],
        isPromotional: true,
        discountPrice: 250,
      ),
      FoodItem(
        id: 'fast_002',
        name: 'Beef Burger',
        category: 'Fast Food',
        price: 300,
        imageUrl: '🍔',
        description: 'Juicy beef patty with fresh vegetables',
        rating: 4.6,
        reviews: 356,
        tags: ['beef', 'popular'],
      ),
      FoodItem(
        id: 'fast_003',
        name: 'Pepperoni Pizza',
        category: 'Fast Food',
        subCategory: 'Most Liked',
        price: 800,
        imageUrl: '🍕',
        description: 'Large pizza with pepperoni and cheese',
        rating: 4.9,
        reviews: 512,
        tags: ['cheese', 'popular'],
      ),
      FoodItem(
        id: 'fast_004',
        name: 'Chicken Wings',
        category: 'Fast Food',
        price: 350,
        imageUrl: '🍗',
        description: '8 pieces of spicy chicken wings',
        rating: 4.5,
        reviews: 234,
        tags: ['chicken', 'spicy'],
      ),
      FoodItem(
        id: 'fast_005',
        name: 'French Fries',
        category: 'Fast Food',
        price: 120,
        imageUrl: '🍟',
        description: 'Crispy golden fries',
        rating: 4.4,
        reviews: 289,
        tags: ['sides', 'crispy'],
      ),
      FoodItem(
        id: 'fast_006',
        name: 'Loaded Fries',
        category: 'Fast Food',
        price: 200,
        imageUrl: '🍟',
        description: 'Fries topped with cheese and chicken',
        rating: 4.7,
        reviews: 198,
        tags: ['cheese', 'chicken'],
        isPromotional: true,
        discountPrice: 180,
      ),
      FoodItem(
        id: 'fast_007',
        name: 'Club Sandwich',
        category: 'Fast Food',
        price: 250,
        imageUrl: '🥪',
        description: 'Triple-decker sandwich with chicken',
        rating: 4.5,
        reviews: 176,
        tags: ['chicken', 'healthy'],
      ),
      FoodItem(
        id: 'fast_008',
        name: 'Hot Dog',
        category: 'Fast Food',
        price: 180,
        imageUrl: '🌭',
        description: 'Classic hot dog with toppings',
        rating: 4.3,
        reviews: 145,
        tags: ['quick'],
      ),

      // ========== CHINESE ==========
      FoodItem(
        id: 'chinese_001',
        name: 'Chicken Fried Rice',
        category: 'Chinese',
        subCategory: 'Most Liked',
        price: 220,
        imageUrl: '🍚',
        description: 'Stir-fried rice with chicken and vegetables',
        rating: 4.6,
        reviews: 267,
        tags: ['rice', 'chicken', 'popular'],
      ),
      FoodItem(
        id: 'chinese_002',
        name: 'Chicken Chow Mein',
        category: 'Chinese',
        price: 240,
        imageUrl: '🍜',
        description: 'Stir-fried noodles with chicken',
        rating: 4.7,
        reviews: 298,
        tags: ['noodles', 'chicken'],
      ),
      FoodItem(
        id: 'chinese_003',
        name: 'Chicken Manchurian',
        category: 'Chinese',
        subCategory: 'Most Liked',
        price: 280,
        imageUrl: '🍗',
        description: 'Crispy chicken in spicy sauce',
        rating: 4.8,
        reviews: 334,
        tags: ['chicken', 'spicy', 'popular'],
      ),
      FoodItem(
        id: 'chinese_004',
        name: 'Spring Rolls',
        category: 'Chinese',
        price: 150,
        imageUrl: '🥟',
        description: 'Crispy vegetable spring rolls',
        rating: 4.4,
        reviews: 187,
        tags: ['vegetarian', 'crispy'],
      ),
      FoodItem(
        id: 'chinese_005',
        name: 'Sweet & Sour Chicken',
        category: 'Chinese',
        price: 300,
        imageUrl: '🍗',
        description: 'Chicken in sweet and sour sauce',
        rating: 4.5,
        reviews: 201,
        tags: ['chicken', 'sweet'],
      ),
      FoodItem(
        id: 'chinese_006',
        name: 'Hakka Noodles',
        category: 'Chinese',
        price: 200,
        imageUrl: '🍜',
        description: 'Spicy stir-fried noodles',
        rating: 4.6,
        reviews: 223,
        tags: ['noodles', 'spicy', 'vegetarian'],
      ),

      // ========== SNACKS ==========
      FoodItem(
        id: 'snack_001',
        name: 'Samosa',
        category: 'Snacks',
        subCategory: 'Most Liked',
        price: 30,
        imageUrl: '🥟',
        description: 'Crispy pastry filled with spiced potatoes',
        rating: 4.7,
        reviews: 456,
        tags: ['vegetarian', 'crispy', 'popular'],
      ),
      FoodItem(
        id: 'snack_002',
        name: 'Pakora',
        category: 'Snacks',
        price: 80,
        imageUrl: '🍤',
        description: 'Mixed vegetable fritters',
        rating: 4.5,
        reviews: 298,
        tags: ['vegetarian', 'crispy'],
        isSeasonal: true,
      ),
      FoodItem(
        id: 'snack_003',
        name: 'Chicken Roll',
        category: 'Snacks',
        subCategory: 'Most Liked',
        price: 150,
        imageUrl: '🌯',
        description: 'Paratha wrap with chicken filling',
        rating: 4.8,
        reviews: 389,
        tags: ['chicken', 'popular'],
      ),
      FoodItem(
        id: 'snack_004',
        name: 'Shawarma',
        category: 'Snacks',
        price: 180,
        imageUrl: '🥙',
        description: 'Middle Eastern wrap with chicken',
        rating: 4.6,
        reviews: 267,
        tags: ['chicken'],
      ),
      FoodItem(
        id: 'snack_005',
        name: 'Dahi Bhalla',
        category: 'Snacks',
        price: 100,
        imageUrl: '🥣',
        description: 'Lentil dumplings in yogurt',
        rating: 4.4,
        reviews: 156,
        tags: ['vegetarian', 'traditional'],
      ),
      FoodItem(
        id: 'snack_006',
        name: 'Chaat',
        category: 'Snacks',
        price: 120,
        imageUrl: '🥗',
        description: 'Spicy street food mix',
        rating: 4.5,
        reviews: 234,
        tags: ['spicy', 'vegetarian'],
      ),

      // ========== BEVERAGES ==========
      FoodItem(
        id: 'bev_001',
        name: 'Mango Shake',
        category: 'Beverages',
        subCategory: 'Seasonal',
        price: 150,
        imageUrl: '🥤',
        description: 'Fresh mango milkshake',
        rating: 4.9,
        reviews: 412,
        tags: ['cold', 'sweet', 'popular'],
        isSeasonal: true,
      ),
      FoodItem(
        id: 'bev_002',
        name: 'Lassi',
        category: 'Beverages',
        price: 100,
        imageUrl: '🥛',
        description: 'Traditional yogurt drink',
        rating: 4.6,
        reviews: 298,
        tags: ['cold', 'traditional'],
      ),
      FoodItem(
        id: 'bev_003',
        name: 'Chai',
        category: 'Beverages',
        subCategory: 'Most Liked',
        price: 50,
        imageUrl: '☕',
        description: 'Traditional milk tea',
        rating: 4.8,
        reviews: 567,
        tags: ['hot', 'popular'],
      ),
      FoodItem(
        id: 'bev_004',
        name: 'Cold Coffee',
        category: 'Beverages',
        price: 180,
        imageUrl: '🧋',
        description: 'Iced coffee with cream',
        rating: 4.7,
        reviews: 345,
        tags: ['cold', 'coffee'],
      ),
      FoodItem(
        id: 'bev_005',
        name: 'Fresh Juice',
        category: 'Beverages',
        price: 120,
        imageUrl: '🧃',
        description: 'Seasonal fresh fruit juice',
        rating: 4.5,
        reviews: 234,
        tags: ['cold', 'healthy'],
      ),
      FoodItem(
        id: 'bev_006',
        name: 'Soft Drink',
        category: 'Beverages',
        price: 80,
        imageUrl: '🥤',
        description: 'Chilled soft drink',
        rating: 4.3,
        reviews: 456,
        tags: ['cold'],
      ),
    ];
  }
}
